merge the rest of upstream changes while making significat switch in templates/jenkins-persistent.yaml for jenkins:lts image

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -28,7 +28,28 @@ function create_from_template {
     shift
   done
 
-  kubectl create -f "${TMP_DIR}/$(basename $FILE)"
+#Error handling improved:
+  ERROR=0
+  for i in $(seq 1 3)
+  do
+    kubectl apply -f "${TMP_DIR}/$(basename $FILE)"
+
+    # TODO What are return values for specific error - timeout/unreachable,... ?
+    if [ $? -ne 0 ]; then
+      echo "Error while creating a template ${TMP_DIR}/$(basename $FILE) !"
+      echo "Retrying..."
+      ERROR=1
+      sleep 10
+    else
+      ERROR=0
+      break
+    fi
+  done
+
+  if [ "$ERROR" -eq 1 ]; then
+    echo "Error while creating a template ${TMP_DIR}/$(basename $FILE) !"
+    exit 1
+  fi
 }
 
 function setup_credentials {
@@ -59,11 +80,11 @@ function wait_for_deployment_ready()
   NAMESPACE=$1
   LABEL=$2
 
-  while true
+  for i in $(seq 1 60)
   do
-    COUNT=$(kubectl get deployment --no-headers -l $LABEL -n $NAMESPACE | awk '{ print $4 }')
+    COUNT=$(kubectl get deployment --no-headers -o=custom-columns=AVAILABLE:.status.availableReplicas -l $LABEL -n $NAMESPACE)
     [ $COUNT -gt 0 ] && break
-    sleep 10
+    sleep 30
   done
 }
 
@@ -78,9 +99,6 @@ function install_helm {
   sudo mv -f linux-amd64/helm /usr/local/bin/
   sudo mv -f linux-amd64/tiller /usr/local/bin/
   cd -
-}
-
-function install_ingress_controller {
 
   # Create service account for tiller part.
   create_from_template templates/helm/helm-rbac.yaml
@@ -88,6 +106,9 @@ function install_ingress_controller {
     --service-account tiller \
     --node-selectors "beta.kubernetes.io/os"="linux"
   helm repo update
+}
+
+function install_ingress_controller {
 
   # Create namespace and nginx ingress pods.
   kubectl create namespace $INGRESS_NAMESPACE
@@ -101,15 +122,18 @@ function install_ingress_controller {
 function wait_for_ingress_controller_public_ip {
   # Wait for public IP address of nginx ingress service
   ROUTER_IP=''
-  COUNTER=1
-  while true
+  for COUNTER in $(seq 1 60)
   do
-    ROUTER_IP=$(kubectl get service -l app=nginx-ingress -n ${INGRESS_NAMESPACE} | grep LoadBalancer | awk '{ print $4 }')
-    [ "$ROUTER_IP" != "<pending>" ] && break
+    ROUTER_IP=$(kubectl get service -o=custom-columns=LB_IP:.status.loadBalancer.ingress[*].ip,TYPE:.spec.type --no-headers -l app=nginx-ingress -n ${INGRESS_NAMESPACE} | grep LoadBalancer | awk '{ print $1 }' | head -n1)
+    [ "$ROUTER_IP" != "<pending>" ] && [ "$ROUTER_IP" != "<none>" ] && break
     echo "Waiting for public IP of ingress router service. (#${COUNTER})"
-    let COUNTER=$COUNTER+1
-    sleep 10
+    sleep 30
   done
+
+  if [ "$ROUTER_IP" == "<pending>" ] || [ "$ROUTER_IP" == "<none>" ]; then
+    echo "ERROR while waiting for LB public IP - no public IP available!"
+    exit 1
+  fi
 }
 
 function install_cert_manager {
@@ -126,9 +150,10 @@ function install_cert_manager {
 
   # CA cluster issuer.
   # Wait till cluster issuer resource can be created.
-  while true; do
+  for i in $(seq 1 60)
+  do
     kubectl apply -f templates/ingress/cluster-issuer.yaml && break
-    sleep 10
+    sleep 30
   done
 }
 
